<template><div><h2 id="搜索引擎" tabindex="-1"><a class="header-anchor" href="#搜索引擎" aria-hidden="true">#</a> 搜索引擎</h2>
<NavCard arr='[{"title":"百度","url":"https://www.baidu.com/","desc":"中文搜索引擎","icon":"/navicon/baidu.ico"},{"title":"必应","url":"https://cn.bing.com/","desc":"优秀的国内外搜索引擎","icon":"/navicon/bing.ico"},{"title":"谷歌","url":"https://www.google.com/","desc":"被墙的国内外搜索引擎","icon":"/navicon/google.ico"}]'></NavCard><h2 id="开源社区" tabindex="-1"><a class="header-anchor" href="#开源社区" aria-hidden="true">#</a> 开源社区</h2>
<NavCard 
arr='[{"title":"Dromara","url":"https://gitee.com/dromara","desc":"孵化HuTool的优秀开源社区","icon":"/navicon/dromara.ico"},{"title":"OSRC","url":"https://www.osrc.com/","desc":"开源运行时社区","icon":"/navicon/oscr.ico"},{"title":"Doocs","url":"https://doocs.gitee.io/#/README_CN","desc":"非常友好的技术社区","icon":"/navicon/doocs.ico"}]'>
</NavCard>
<h2 id="在线工具" tabindex="-1"><a class="header-anchor" href="#在线工具" aria-hidden="true">#</a> 在线工具</h2>
<NavCard arr='[{"title":"下载加速","url":"https://toolwa.com/github/","desc":"Github下载加速","icon":"/navicon/github.ico"},{"title":"菜鸟工具","url":"https://c.runoob.com/","desc":"菜鸟教程提供的工具集","icon":"/navicon/cainiao.ico"},{"title":"工具集","url":"https://tool.oschina.net/","desc":"开源中国提供的工具集","icon":"/navicon/oschina.ico"},{"title":"程序员","url":"https://tool.lu/","desc":"程序员的工具箱","icon":"/navicon/chengxuyuan.ico"},{"title":"脚本之家","url":"http://tools.jb51.net/","desc":"脚本之家提供的工具箱","icon":"/navicon/jiaoben.ico"},{"title":"W3C","url":"https://123.w3cschool.cn/webtools","desc":"W3C School旗下提供的工具箱","icon":"/navicon/w3c.ico"},{"title":"云转换","url":"https://cloudconvert.com/","desc":"在线转化","icon":"/navicon/yun.png"}]'></NavCard><h2 id="在线教程" tabindex="-1"><a class="header-anchor" href="#在线教程" aria-hidden="true">#</a> 在线教程</h2>
<NavCard arr='[{"title":"Electron","url":"https://www.electronjs.org/","desc":"electron官方文档","icon":"/navicon/electron.svg"},{"title":"Vite","url":"https://vitejs.cn/","desc":"Vite中文网","icon":"/navicon/vite.svg"},{"title":"Vue3","url":"https://vuejs.org/","desc":"Vue3官网","icon":"/navicon/vue.svg"},{"title":"React","url":"https://react.docschina.org/","desc":"React中文网","icon":"/navicon/react.svg"},{"title":"菜鸟教程","url":"https://www.runoob.com/","desc":"菜鸟在线教程","icon":"/navicon/runoob.ico"}]'></NavCard><h2 id="文档相关" tabindex="-1"><a class="header-anchor" href="#文档相关" aria-hidden="true">#</a> 文档相关</h2>
<NavCard arr='[{"title":"在线MD","url":"https://markdown.com.cn/editor/","desc":"在线编写MarkDown","icon":"/navicon/github.ico"},{"title":"hope","url":"https://vuepress-theme-hope.gitee.io/v2/zh/","desc":"一个优秀静态博客搭建工具","icon":"/navicon/hope.svg"}]'></NavCard><h2 id="其他导航" tabindex="-1"><a class="header-anchor" href="#其他导航" aria-hidden="true">#</a> 其他导航</h2>
<NavCard arr='[{"title":"极下解析","url":"https://jixia.ltd/","desc":"百度云外链解析","icon":"/navicon/jixia.ico"},{"title":"MyOctoCat","url":"https://myoctocat.com/","desc":"程序员头像","icon":"/navicon/github.ico"},{"title":"LeetCode","url":"https://leetcode.cn/","desc":"刷题网站","icon":"/navicon/leetcode.ico"},{"title":"Jar包下载","url":"https://search.maven.org/","desc":"Jar包个版本下载","icon":"/navicon/jar.ico"},{"title":"ghelper","url":"http://ghelper.net/","desc":"看世界","icon":"/navicon/ghelper.png"},{"title":"Maven仓库","url":"https://mvnrepository.com/","desc":"Maven官方仓库","icon":"/navicon/mvn.ico"}]'></NavCard></div></template>


